image: Visual Studio 2017

skip_branch_with_pr: true

build_script:
 - cmd: dotnet restore
 - cmd: dotnet build -c Release

test_script:
 - dotnet test vcr-sharp-tests/VCRSharp.Tests.csproj -c Release

after_test:
 - dotnet run -p VCRSharp.Benchmarks

artifacts:
 - path: BenchmarkDotNet.Artifacts\**\*
